# Product
###
GET http://127.0.0.1:8000/api/v1/products/
###

POST http://127.0.0.1:8000/api/v1/products/
Content-Type: application/json

{
  "title": "Помидор3",
  "description": "Лучшие помидоры на рынке"
}
###

GET http://127.0.0.1:8000/api/v1/products/3/

###

PATCH http://127.0.0.1:8000/api/v1/products/2/
Content-Type: application/json

{
  "title": "new title"
}

###

DELETE http://127.0.0.1:8000/api/v1/products/2/

###
# filters
GET http://127.0.0.1:8000/api/v1/products/?title=title1

###

GET http://127.0.0.1:8000/api/v1/products/?search=first

###
# filters ordering descending
GET http://127.0.0.1:8000/api/v1/products/?search=description&ordering=-id
###
# filters ordering acsending
GET http://127.0.0.1:8000/api/v1/products/?search=description&ordering=id
###
# filters ordering acsending
GET http://127.0.0.1:8000/api/v1/products/?search=description&ordering=title,id

###
# PAginator
GET http://127.0.0.1:8000/api/v1/products/?page=1

###
# LimitOffsetPagination
GET http://127.0.0.1:8000/api/v1/products/?limit=2
###
GET http://127.0.0.1:8000/api/v1/products/?limit=2&offser=3
###
# Stock
GET http://127.0.0.1:8000/api/v1//stocks/
###
POST http://127.0.0.1:8000/api/v1//stocks/
Content-Type: application/json

{
  "address": "м1ой адрес не дом и не улица, мой адрес сегодня такой: www.ленинград-спб.ru3",
  "positions": [
    {
      "product": 7,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 8,
      "quantity": 100,
      "price": 180
    }
  ]
}

###
PATCH http://127.0.0.1:8000/api/v1/stocks/5/
Content-Type: application/json

{
  "positions": [
    {
      "product": 7,
      "quantity": 100,
      "price": 130.80
    },
    {
      "product": 8,
      "quantity": 243,
      "price": 145
    }
  ]
}

###
GET http://127.0.0.1:8000/api/v1/stocks/?products=8